// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "match_server/Match.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>
#include <thrift/TToString.h>
#include <thrift/concurrency/ThreadManager.h>
#include <thrift/concurrency/ThreadFactory.h>
#include <thrift/server/TThreadedServer.h>
#include <thrift/server/TThreadPoolServer.h>
#include <thrift/transport/TSocket.h>
#include <thrift/transport/TTransportUtils.h>

#include <iostream>
#include <thread>
#include <mutex>
#include <queue>
#include <vector>
#include <condition_variable>
#include <unistd.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::match_service;
using namespace std;

struct Task{
    User user;
    string type;//记录add或者remove
};

struct Queue{
    queue<Task> q;
    mutex m;
    condition_variable cv;
}task_queue;

class Pool{
    private:
        vector<User> users;
        vector<int> wt;//等待时间
    public:
        void save_result(int a,int b){
            printf("Match result is %d and %d.\n",a,b);
        }

        bool check_match(uint32_t i,uint32_t j){
            auto a=users[i], b=users[j];

            int dif = abs(a.score - b.score);
            int a_dif = wt[i] * 50;
            int b_dif = wt[i] * 50;

            return dif <= a_dif && dif <= b_dif;
        }

        void match(){
            for(uint32_t i= 0;i<wt.size(); i++)
                wt[i] ++;//等待时间+1

            while(users.size()>1){
                bool flag = true;
                for(uint32_t i=0;i<users.size(); i++){
                    for(uint32_t j = i + 1; j<users.size(); j++){
                        if(check_match(i, j)){
                            save_result(users[i].id, users[j].id);
                            users.erase(users.begin() + j);
                            users.erase(users.begin() + i);
                            wt.erase(wt.begin() + j);
                            wt.erase(wt.begin() + i);
                            flag = false;
                            break;
                        }
                    if(!flag) break;//如果匹配上则退出循环
                    }
                }
                if(flag) break;//如果没有匹配上就退出匹配
            }
        }

        void add(User user){
            users.push_back(user);
            wt.push_back(0);
        }

        void remove(User user){
            for(uint32_t i=0; i<users.size(); i++){
                if(users[i].id == user.id){
                    users.erase(users.begin() + i);
                    wt.erase(wt.begin() + i);
                    break;
                }
            }
        }
}pool;


class MatchHandler : virtual public MatchIf {
    public:
        MatchHandler() {
            // Your initialization goes here
        }

        int32_t add_user(const User& user, const std::string& info) {
            // Your implementation goes here
            printf("add_user\n");

            unique_lock<mutex> lock(task_queue.m);
            task_queue.q.push({user,"add"});
            task_queue.cv.notify_all();

            return 0;
        }

        int32_t remove_user(const User& user, const std::string& info) {
            // Your implementation goes here
            printf("remove_user\n");

            unique_lock<mutex> lock(task_queue.m);
            task_queue.q.push({user,"remove"});
            task_queue.cv.notify_all();

            return 0;
        }
};

class MatchCloneFactory : virtual public MatchIfFactory {
    public:
        ~MatchCloneFactory() override = default;
        MatchIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) override
        {
            std::shared_ptr<TSocket> sock = std::dynamic_pointer_cast<TSocket>(connInfo.transport);
            /*cout << "Incoming connection\n";
            cout << "\tSocketInfo: "  << sock->getSocketInfo() << "\n";
            cout << "\tPeerHost: "    << sock->getPeerHost() << "\n";
            cout << "\tPeerAddress: " << sock->getPeerAddress() << "\n";
            cout << "\tPeerPort: "    << sock->getPeerPort() << "\n";*/
            return new MatchHandler;
        }
        void releaseHandler( MatchIf* handler) override {
            delete handler;
        }
};

void match_task(){
    while (true){
        unique_lock<mutex> lock(task_queue.m);
        if(task_queue.q.empty()){
            task_queue.m.unlock();
            pool.match();
            sleep(1);//每一秒匹配一次
        }
        else {
            auto task = task_queue.q.front();
            task_queue.q.pop();
            task_queue.m.unlock();

            if(task.type == "add")
                pool.add(task.user);
            if(task.type == "remove")
                pool.remove(task.user);
        }
    }
}

int main(int argc, char **argv) {
    TThreadedServer server(
            std::make_shared<MatchProcessorFactory>(std::make_shared<MatchCloneFactory>()),
            std::make_shared<TServerSocket>(9090), //port
            std::make_shared<TBufferedTransportFactory>(),
            std::make_shared<TBinaryProtocolFactory>());

    cout<<"Start Match Server"<<endl;

    thread matching_thread(match_task);

    server.serve();
    return 0;
}

